### ISSUE TITLE
Webhook support?

### ISSUE THREAD

**Issue by IngwiePhoenix** [leonklingele/github-release-checker#2]
Hello there!

I would love to connect this to [Gotify](https://gotify.net/docs/more-pushmsg) and/or [Matrix](https://github.com/nim65s/matrix-webhook). Whilst I could use a dummy SMTP bridge for this, it'd be pretty neat to configure a webhook handler that sends a POST when a new release is found.

For example:

```toml
[webhook]
host = "http://localhost:8008/message?token=abcdef"
message = "{'title': '$repo_title', 'message': 'New version: $version'}"
```

Kind regards,
Ingwie
